# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 17:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('cat2', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('cat3', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('cat4', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('mouse', models.IntegerField(default=59, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('catTurn', models.BooleanField(default=True)),
                ('catUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamecatUsers', to=settings.AUTH_USER_MODEL)),
                ('mouseUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamemouseUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('target', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='server.Game')),
            ],
        ),
    ]
